databases:
  - name: unight
    databaseName: unightdb
    user: postgres

services:
  - type: web
    name: unight
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: unight
          property: postgresql://unightdb:12345@localhost:5432/unight
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4