# Generated by Django 4.0.6 on 2023-01-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_comment_remove_person_city_remove_person_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.TextField(default='no comments yet'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
