# Generated by Django 4.0.6 on 2023-01-21 01:40

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_post_comments_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('post_id', models.CharField(max_length=500)),
                ('comment', models.TextField()),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
