# Generated by Django 4.0.6 on 2023-01-23 20:49

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_comment_id_remove_post_comments_post_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('post_id', models.CharField(max_length=500)),
                ('comment', models.TextField()),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
