# Generated by Django 4.0.6 on 2023-01-24 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
